// ============================================
// CENTRALIZED TAG SYSTEM
// ============================================

// Tag icon mapping
const TAG_ICONS = {
    'jack-declining': '📉',
    'jack-violence': '🔪',
    'jack-supernatural': '👻',
    'jack-drunk': '🥃',
    'wendy-discovering': '🔍',
    'wendy-defending': '🛡️',
    'wendy-supernatural': '👤',
    'danny-shining': '✨',
    'danny-endangered': '⚠️',
    'danny-tony': '🗣️',
    'halloran-shining': '🔮',
    'halloran-rescue': '🚁',
    'hotel-tour': '🚶',
    'gold-ballroom': '🏛️',
    'room-237': '🚪',
    'maze': '🌿',
    'pantry': '🔒',
    'apartment': '🏠',
    'colorado-lounge': '🪑',
    'bathroom': '🚿',
    'ghost-encounter': '👻',
    'ghost-party': '🎭',
    'lloyd': '🍸',
    'grady': '👔',
    'grady-twins': '👯',
    'woman-237': '🛁',
    'blood-elevator': '🩸',
    'possession': '😈',
    'shining-vision': '👁️',
    'time-distortion': '⏰',
    'heres-johnny': '🚪',
    'all-work-no-play': '📝',
    'red-rum': '🪞',
    'twins': '👯',
    'photograph': '📸',
    'baseball-bat': '⚾',
    'tricycle': '🚲',
    'always-been-caretaker': '♾️',
    'footprint-trick': '👣',
    'physical-violence': '💥',
    'threatened-violence': '⚔️',
    'psychological-horror': '🌀',
    'murder': '🔪',
    'chase': '🏃',
    'weapon': '🪓',
    'iconic-dialogue': '💬',
    'gaslighting': '🌫️',
    'dark-humor': '😏',
    'arrival': '🚗',
    'interview': '📋',
    'tour': '🚶',
    'closing-day': '👋',
    'isolation-begins': '🏔️',
    'one-month-later': '📅',
    'escalation': '📈',
    'breaking-point': '💔',
    'crisis': '🚨',
    'climax': '⚡',
    'resolution': '✓',
    'epilogue': '🎬',
    'isolation': '❄️',
    'family-breakdown': '💔',
    'alcoholism': '🍺',
    'violence-history': '📜',
    'writer-block': '✍️',
    'responsibility': '⚖️',
    'parent-child': '👨‍👦',
    'marriage-strain': '💍',
    'typewriter': '⌨️',
    'axe': '🪓',
    'knife': '🔪',
    'radio': '📻',
    'snowcat': '🚜',
    'telephone': '☎️',
    'outside-contact': '📡',
    'radio-call': '📻',
    'phone-call': '☎️',
    'contact-blocked': '🚫',
    'storm': '🌨️',
    'snow': '❄️',
    'trapped-by-weather': '🌨️',
    'callback': '↩️',
    'foreshadowing': '🔮',
    'parallel': '⫴',
    'intercutting': '✂️',
};

// Tag groups organized by category
const TAG_GROUPS = {
    'Character Arcs': ['jack-declining', 'jack-violence', 'jack-supernatural', 'jack-drunk', 'wendy-discovering', 'wendy-defending', 'wendy-supernatural', 'danny-shining', 'danny-endangered', 'danny-tony', 'halloran-shining', 'halloran-rescue'],
    'Locations': ['hotel-tour', 'gold-ballroom', 'room-237', 'maze', 'pantry', 'apartment', 'colorado-lounge', 'bathroom'],
    'Supernatural': ['ghost-encounter', 'ghost-party', 'lloyd', 'grady', 'grady-twins', 'woman-237', 'blood-elevator', 'possession', 'shining-vision', 'time-distortion'],
    'Iconic Moments': ['heres-johnny', 'all-work-no-play', 'red-rum', 'twins', 'photograph', 'baseball-bat', 'tricycle', 'always-been-caretaker', 'footprint-trick'],
    'Violence & Horror': ['physical-violence', 'threatened-violence', 'psychological-horror', 'murder', 'chase', 'weapon'],
    'Key Dialogue': ['iconic-dialogue', 'gaslighting', 'dark-humor'],
    'Plot Progression': ['arrival', 'interview', 'tour', 'closing-day', 'isolation-begins', 'one-month-later', 'escalation', 'breaking-point', 'crisis', 'climax', 'resolution', 'epilogue'],
    'Themes': ['isolation', 'family-breakdown', 'alcoholism', 'violence-history', 'writer-block', 'responsibility', 'parent-child', 'marriage-strain'],
    'Objects': ['typewriter', 'axe', 'knife', 'radio', 'snowcat', 'telephone'],
    'Communication': ['outside-contact', 'radio-call', 'phone-call', 'contact-blocked'],
    'Weather': ['storm', 'snow', 'trapped-by-weather'],
    'Structure': ['callback', 'foreshadowing', 'parallel', 'intercutting'],
};

// Canonical tag order (flattened from groups)
const ALL_TAGS_ORDERED = [
    'jack-declining', 'jack-violence', 'jack-supernatural', 'jack-drunk', 'wendy-discovering', 'wendy-defending', 'wendy-supernatural', 'danny-shining', 'danny-endangered', 'danny-tony', 'halloran-shining', 'halloran-rescue', 'hotel-tour', 'gold-ballroom', 'room-237', 'maze', 'pantry', 'apartment', 'colorado-lounge', 'bathroom', 'ghost-encounter', 'ghost-party', 'lloyd', 'grady', 'grady-twins', 'woman-237', 'blood-elevator', 'possession', 'shining-vision', 'time-distortion', 'heres-johnny', 'all-work-no-play', 'red-rum', 'twins', 'photograph', 'baseball-bat', 'tricycle', 'always-been-caretaker', 'footprint-trick', 'physical-violence', 'threatened-violence', 'psychological-horror', 'murder', 'chase', 'weapon', 'iconic-dialogue', 'gaslighting', 'dark-humor', 'arrival', 'interview', 'tour', 'closing-day', 'isolation-begins', 'one-month-later', 'escalation', 'breaking-point', 'crisis', 'climax', 'resolution', 'epilogue', 'isolation', 'family-breakdown', 'alcoholism', 'violence-history', 'writer-block', 'responsibility', 'parent-child', 'marriage-strain', 'typewriter', 'axe', 'knife', 'radio', 'snowcat', 'telephone', 'outside-contact', 'radio-call', 'phone-call', 'contact-blocked', 'storm', 'snow', 'trapped-by-weather', 'callback', 'foreshadowing', 'parallel', 'intercutting'
];

// Total tags: 85
